import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Workout Composer v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/favicon.ico" />
      </Head>

      <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>
        Click
      </button>
    </>
  );
};

export default Home;
