import { useState } from 'react';
import { ToastManager } from '../../../shared/managers/toast-manager';
import { saveWorkout } from '../actions';
import { useWorkoutStore } from '../workout-store';
import { useForm } from 'react-hook-form';
import { useSearchParams } from 'next/navigation';

type ShareModalComponentProps = {
    onCancel: () => void;
};

type ShareForm = {
    id?: string;
    secret: string;
};

export const ShareModalComponent = (props: ShareModalComponentProps) => {
    const { days } = useWorkoutStore();
    const [searchParams] = useSearchParams();
    const {
        register,
        handleSubmit,
        formState: { errors },
    } = useForm<ShareForm>({
        defaultValues: {
            id: (searchParams ?? [])[1] ?? '',
        },
    });
    const [shareLoading, setShareLoading] = useState(false);

    const onShare = async (data: ShareForm) => {
        if (!data.secret) {
            return;
        }
        try {
            setShareLoading(true);
            const workoutId = await saveWorkout({ id: data.id, secret: data.secret, days });
            navigator.clipboard.writeText(`${window.location.href}workout-composer?id=${workoutId}`);
            window.history.pushState({}, document.title, `workout-composer?id=${workoutId}`);
            ToastManager.showInfo('💫 Workout link copied!');
            props.onCancel();
        } catch (err) {
            ToastManager.showError(`Failed to save workout: ${err}`);
            setShareLoading(false);
        }
    };

    const onExportText = async () => {
        let textData = '';
        for (const day of days) {
            if (textData.length > 0) {
                textData += '\n\n';
            }
            textData += `${day.name}`;
            for (const task of day.tasks) {
                textData += `\n\t${task.name} ${task.sets} x ${task.reps}`;
                if (task.description) {
                    textData += ` (${task.description})`;
                }
            }
        }
        if (navigator.share) {
            await navigator.share({ title: 'Workout', text: textData });
        } else {
            const element = document.createElement('a');
            const textFile = new Blob([textData], { type: 'text/plain' });
            const url = URL.createObjectURL(textFile);
            element.href = url;
            element.download = 'workout.txt';
            document.body.appendChild(element);
            element.click();
            document.body.removeChild(element);
            URL.revokeObjectURL(url);
        }
    };

    return (
        <div className="modalBackdrop">
            <div className="modalWrapper">
                <form onSubmit={handleSubmit(onShare)} className="formWrapper">
                    <h3 className="subtitle bold" style={{ marginBottom: '1rem' }}>
                        Share Workout
                    </h3>
                    <fieldset>
                        <label className="formLabel" htmlFor="name">
                            ID (empty for autogenerated)
                        </label>
                        <input {...register('id')} id="id" className="formInput" />
                    </fieldset>
                    <fieldset>
                        <label className="formLabel" htmlFor="name">
                            Master Key
                        </label>
                        <input
                            {...register('secret', { required: true })}
                            id="secret"
                            type="password"
                            className="formInput"
                        />
                        {errors.secret && <p className="formError">Secret is required</p>}
                    </fieldset>
                    <div className="formActionsWrapper">
                        <button disabled={shareLoading} type="submit" className="formBtnSubmit">
                            Confirm
                        </button>
                        <button
                            onClick={props.onCancel}
                            disabled={shareLoading}
                            type="button"
                            className="formBtnCancel">
                            Cancel
                        </button>
                    </div>
                    <p className="formLabel" style={{ margin: '1rem 0 0 0', textAlign: 'center' }}>
                        or
                    </p>
                    <div className="formActionsWrapper">
                        <button
                            onClick={onExportText}
                            disabled={shareLoading}
                            type="button"
                            className="formBtnSubmit">
                            Export as text
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};
